import os
import numpy as np
import pandas as pd
from snakemake.utils import validate


# Set your specific experimental configuration here
configfile: "config/example.yaml"


# Image used when `snakemake --use-singularity` (or --use-apptainer) is set.
# Built and published by .github/workflows/build-container.yml on tag push.
# The `dev` tag tracks the latest container-branch build; release tags
# (v0.2.x) get pinned URIs once we cut them.
containerized: "docker://ghcr.io/odcambc/dumpling:dev"


# Include rules from other files
include: "rules/common.smk"
include: "rules/asm.smk"
include: "rules/enrich.smk"
include: "rules/filter.smk"
include: "rules/map.smk"
include: "rules/process.smk"
include: "rules/baseline_qc.smk"
include: "rules/qc.smk"
include: "rules/ref.smk"
include: "rules/rosace.smk"
include: "rules/lilace.smk"
include: "rules/rosace_aa.smk"
include: "rules/deposit.smk"


# Pseudo-rule for running analysis
rule all:
    input:
        get_input,
