rule process_counts:
    input:
        expand(
            "results/{{experiment}}/gatk/{samples}.variantCounts",
            samples=samples
        ),
    output:
        expand(
            "results/{{experiment}}/processed_counts/{samples}.tsv",
            samples=samples
        )
    params:
        remove_zeros=config["remove_zeros"],
        regenerate_variants=config["regenerate_variants"],
        samples=samples,
        gatk_dir="results/{experiment}/gatk/"
    benchmark:
        "benchmarks/{experiment}/{experiment}.process_counts.benchmark.txt"
    log:
        "logs/{experiment}/scripts/{experiment}.process_counts.log",
    script:
        "scripts/process_counts.py"