$schema: "https://json-schema.org/draft/2020-12/schema"
description: DMS pipeline configuration file
properties:
  data_dir:
    type: string
    description: directory containing reads
  experiment:
    type: string
    description: sample condition that will be compared during differential expression analysis (e.g. a treatment, a tissue time, a disease)
  experiment_file:
    type: string
    description: Location of experiment setup definition file in CSV format
  samples:
    type: array
    description: Array of experiment file names (truncated at lane number)
  ref_dir:
    type: string
    description: directory where reference files are located
  reference:
    type: string
    description: reference file name
  orf:
    type: string
    description: "ORF coordinates in reference file. Format: start-stop"
  kmers:
    type: integer
    default: 15
    description: kmer length for bbduk
  min_q:
    type: integer
    default: 30
    description: minimum Q score for bases to be analyzed by GATK
  sam:
    type: string
    default: "1.3"
    description: cigar string version for bbmap - 1.3 uses M for = or X, and 1.4 uses = or X.
  samtools_local:
    type: boolean
    default: false
    description: Flag for whether to use local samtools or wrapper version.
  rosace_local:
    type: boolean
    default: false
    description: Flag for whether to use ROSACE installed on system-wide R or through a conda-controlled R environment.
  adapters:
    type:
      - string
      - array
    description: adapter file(s) locations for bbduk. Can be single file string or array of files.
  contaminants:
    type:
      - string
      - array
    description: contaminant reference file(s) locations for bbduk. Can be single file string or array of files.
  mem:
    type: integer
    default: 16
    description: memory for bbtools (in Gb)
  mem_fastqc:
    type: integer
    default: 1024
    description: memory for bbtools (in Mb)
  enrich2:
    type: boolean
    default: false
    description: Flag for whether to run Enrich2 in addition to Rosace.
  remove_zeros:
    type: boolean
    default: false
    description: Flag for whether to remove unobserved and zero-count variants before processing with Enrich.
  regenerate_variants:
    type: boolean
    default: false
    description: Flag for whether to regenerate the designed variants file from an oligo list.
  noprocess:
    type: boolean
    default: false
    description: Flag for whether called variants are filtered or not.
  run_qc:
    type: boolean
    default: true
    description: Flag for whether QC should be performed.
  baseline_condition:
    type: string
    default: ""
    description: Name of condition containing baseline samples. Scores will not be generated for this condition.
  max_deletion_length:
    type: integer
    default: 3
    description: Maximum length (in codons) of designed deletion in library.

required:
  - data_dir
  - experiment
  - experiment_file
  - ref_dir
  - reference
  - orf